### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by BogdanP17** [BogdanP17/Love-to-run#1]
In order to **receive benefits** as a **role**, i can **goal/desire**

**Future: Publish a Poll**

**User Story 1:**
 In order to collect users feedback, as a administrator, i can publish a poll.

**User Story 2:**
 In order to automatically hide the poll as an administator, i can pick the expiry date while publishing the poll.

**Futures: Submit a Poll Respone**

**User Story 1:**
 In order to provide my opinion with regards to a certain running topic or event as a user, i can select and submit an answer from the poll.

**User Story 2:**
 In order to provide anonymous feedback as a user, i can choose to hide my identity in the poll response.

**Acceptance criteria:**

- The option should be privided as a checkbox
- The checkbox should be "checked" by default
- The option should appear next to the submit button

**Tasks:**

- [ ] Create a new field in the model to tack the username
- [ ] Test the functionality
- [ ] Update the controller function
